language:
  - java

before_install:
# Install Testspace Runner
  - ./testspace_install.sh
  - export PATH="${HOME}/testspace:${PATH}"

script:
  - mvn clean compile
  - mvn cobertura:cobertura -Dcobertura.report.format=xml

# Publish Test Results along with Coverage
  - testspace publish target/surefire-reports/TEST-TestSuite.xml target/site/cobertura/coverage.xml ${TESTSPACE_URL}
