name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - name: Build
        run: |
          mvn clean compile
          mvn pmd:pmd
      - name: Test
        run: |
          mvn cobertura:cobertura -Dcobertura.report.format=xml
      - name: Push
        run: |
          testspace target/pmd.xml [Tests]target/surefire-reports/TEST-TestSuite.xml target/site/cobertura/coverage.xml
        if: always()
